config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/csr',    to: 'static_pages#csr'
  get  '/about',   to: 'static_pages#about'
  get  '/career', to: 'static_pages#career'
  get  '/investor', to: 'static_pages#investor'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def hello
    render html: "hello, world!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  
  def about
  end

  def csr
  end
  
  def career
  end
  
  def investor
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.       # Documentation comment
  def full_title(page_title = '')                     # Method def, optional arg
    base_title = "Barmin Pacific"  # Variable assignment
    if page_title.empty?                              # Boolean test
      base_title                                      # Implicit return
    else
      page_title + " | " + base_title                 # String concatenation
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
  
  <% if false %>

<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>






	<footer id="footer" class="top-space">

		<div class="footer1">
			<div class="container">
				<div class="row">
					
					<div class="col-md-3 widget">
						<h3 class="widget-title">Contact</h3>
						<div class="widget-body">
							<p>+234 23 9873237<br>
								<a href="mailto:#">sales@barminpacific.com</a><br>
								<br>
								234 Hidden Pond Road, Ashland City, TN 37015
							</p>	
						</div>
					</div>

					<div class="col-md-3 widget">
						<h3 class="widget-title">Follow me</h3>
						<div class="widget-body">
							<p class="follow-me-icons">
								<a href=""><i class="fa fa-twitter fa-2"></i></a>
								<a href=""><i class="fa fa-dribbble fa-2"></i></a>
								<a href=""><i class="fa fa-github fa-2"></i></a>
								<a href=""><i class="fa fa-facebook fa-2"></i></a>
							</p>	
						</div>
					</div>

					<div class="col-md-6 widget">
						<h3 class="widget-title">Our Business Philosophy</h3>
						<div class="widget-body">
							<p>Maximize long-term return to shareowners while being mindful of our overall responsibilities.</p>
							<p>Focus on needs of our consumers, customers and manufacturer partners</p>
							<p>Get out into the market and listen, observe and learn</p>
							<p>Focus on execution in the marketplace every day</p>
							<p>Possess a world view</p>
							<p>Be insatiably curious</p>
						</div>
					</div>

				</div> <!-- /row of widgets -->
			</div>
		</div>

		<div class="footer2">
			<div class="container">
				<div class="row">
					
					<div class="col-md-6 widget">
						<div class="widget-body">
							<p class="simplenav">
								<a href="#">Home</a> | 
								<a href="about.html">About</a> |
								<a href="sidebar-right.html">Sidebar</a> |
								<a href="contact.html">Contact</a> |
								<b><a href="signup.html">Sign up</a></b>
							</p>
						</div>
					</div>

					<div class="col-md-6 widget">
						<div class="widget-body">
							<p class="text-right">
								Copyright &copy; 2013-2017, Barmin Pacific <a href="http://Barminpacific.com/" rel="designer">Barmin Creative, Co</a> 
							</p>
						</div>
					</div>

				</div> <!-- /row of widgets -->
			</div>
		</div>

	</footer>	
	
	
	<% end %>
	
	
    <footer id="myFooter">
        <div class="container">
            <div class="row">
                <div class="col-sm-3">
                    <h2 class="logo"><a href="#"> Barmin Pacific </a></h2>
                </div>
                <div class="col-sm-2">
                    <h5>Get started</h5>
                    <ul>
                        <li><a href="#">Home</a></li>
                        <li><a href="#">Sign up</a></li>
                        <li><a href="#">Downloads</a></li>
                    </ul>
                </div>
                <div class="col-sm-2">
                    <h5>About us</h5>
                    <ul>
                        <li><a href="#">Company Information</a></li>
                        <li><a href="#">Contact us</a></li>
                        <li><a href="#">Reviews</a></li>
                    </ul>
                </div>
                <div class="col-sm-2">
                    <h5>Support</h5>
                    <ul>
                        <li><a href="#">FAQ</a></li>
                        <li><a href="#">Help desk</a></li>
                        <li><a href="#">Forums</a></li>
                    </ul>
                </div>
                <div class="col-sm-3">
                    <div class="social-networks">
                        <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
                        <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
                        <a href="#" class="google"><i class="fa fa-google-plus"></i></a>
                    </div>
                    <button type="button" class="btn btn-default">Contact us</button>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
								Copyright &copy; 2013-2017 <a href="http://Barminpacific.com/" rel="designer">Barmin Creative, Co</a>
        </div>
    </footer>

app/views/layouts/_header.html.erb
<div class="container">
    <header id="slider">
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
          <!-- Slide One - Set the background image for this slide in the line below -->
          <div class="carousel-item active" style="background-image: url('http://placehold.it/1900x1080')">
            <div class="carousel-caption d-none d-md-block">
              <h3>First Slide</h3>
              <p>This is a description for the first slide.</p>
            </div>
          </div>
          <!-- Slide Two - Set the background image for this slide in the line below -->
          <div class="carousel-item" style="background-image: url('http://placehold.it/1900x1080')">
            <div class="carousel-caption d-none d-md-block">
              <h3>Second Slide</h3>
              <p>This is a description for the second slide.</p>
            </div>
          </div>
          <!-- Slide Three - Set the background image for this slide in the line below -->
          <div class="carousel-item" style="background-image: url('http://placehold.it/1900x1080')">
            <div class="carousel-caption d-none d-md-block">
              <h3>Third Slide</h3>
              <p>This is a description for the third slide.</p>
            </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </header>
</div>

app/views/layouts/_nav.html.erb
     <!-- logo top tips -->
    
      <div class="container">
            <%= link_to image_tag("bp_logo.png"), root_path  %>
      </div>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-danger">
      <div class="container">
        
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="about.html">About</a>
            </li>
            <li class="nav-item">
              <%= link_to "Product", about_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Contact", about_path, class: "nav-link" %>
            </li>
            
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Portfolio
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
                <%= link_to "Barmin Pacific", root_path, class: "dropdown-item" %>
                <a class="dropdown-item" href="portfolio-1-col.html">1 Column Portfolio</a>
                <a class="dropdown-item" href="portfolio-2-col.html">2 Column Portfolio</a>
                <a class="dropdown-item" href="portfolio-3-col.html">3 Column Portfolio</a>
              </div>
            </li>
            
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownBlog" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Blog
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownBlog">
                <a class="dropdown-item" href="blog-home-1.html">Blog Home 1</a>
                <a class="dropdown-item" href="blog-home-2.html">Blog Home 2</a>
                <a class="dropdown-item" href="blog-post.html">Blog Post</a>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  


  <body>
    
    
    <header id="header">
    
        <%= render 'layouts/nav' %>
        <%= render partial: "layouts/header" if current_page?('/')  %>
    </header>
    
    
    <section id="content">
      <div class="container">
        <%= yield %>
      </div>
    </section>
    
    <footer id="footer">
      <div class="container-fluid">
        <%= render 'layouts/footer' %>
      </div>
    </footer>
  </body>







</html>

app/views/layoutsf/_footer.html.erb
  
  <% if false %>

<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>



<% end %>



	<footer id="footer" class="top-space">

		<div class="footer1">
			<div class="container">
				<div class="row">
					
					<div class="col-md-3 widget">
						<h3 class="widget-title">Contact</h3>
						<div class="widget-body">
							<p>+234 23 9873237<br>
								<a href="mailto:#">sales@barminpacific.com</a><br>
								<br>
								234 Hidden Pond Road, Ashland City, TN 37015
							</p>	
						</div>
					</div>

					<div class="col-md-3 widget">
						<h3 class="widget-title">Follow me</h3>
						<div class="widget-body">
							<p class="follow-me-icons">
								<a href=""><i class="fa fa-twitter fa-2"></i></a>
								<a href=""><i class="fa fa-dribbble fa-2"></i></a>
								<a href=""><i class="fa fa-github fa-2"></i></a>
								<a href=""><i class="fa fa-facebook fa-2"></i></a>
							</p>	
						</div>
					</div>

					<div class="col-md-6 widget">
						<h3 class="widget-title">Our Business Philosophy</h3>
						<div class="widget-body">
							<p>Maximize long-term return to shareowners while being mindful of our overall responsibilities.</p>
							<p>Focus on needs of our consumers, customers and manufacturer partners</p>
							<p>Get out into the market and listen, observe and learn</p>
							<p>Focus on execution in the marketplace every day</p>
							<p>Possess a world view</p>
							<p>Be insatiably curious</p>
						</div>
					</div>

				</div> <!-- /row of widgets -->
			</div>
		</div>

		<div class="footer2">
			<div class="container">
				<div class="row">
					
					<div class="col-md-6 widget">
						<div class="widget-body">
							<p class="simplenav">
								<a href="#">Home</a> | 
								<a href="about.html">About</a> |
								<a href="sidebar-right.html">Sidebar</a> |
								<a href="contact.html">Contact</a> |
								<b><a href="signup.html">Sign up</a></b>
							</p>
						</div>
					</div>

					<div class="col-md-6 widget">
						<div class="widget-body">
							<p class="text-right">
								Copyright &copy; 2013-2017, Barmin Pacific <a href="http://Barminpacific.com/" rel="designer">Barmin Creative, Co</a> 
							</p>
						</div>
					</div>

				</div> <!-- /row of widgets -->
			</div>
		</div>

	</footer>	

app/views/layoutsf/_header.html.erb
<% if false %>

<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",    root_path %></li>
        <li><%= link_to "Help",    help_path %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>


<% end %>


	<!-- Fixed navbar -->
	<div class="navbar navbar-inverse navbar-fixed-top headroom" >
		<div class="container">
			<div class="navbar-header">
				<!-- Button for smallest screens -->
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
				<%= link_to "Barmin Pacific & Co", root_path, id: "logo" %>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav pull-right">
        	<li><%= link_to "Home",    root_path %></li>
        	
					<li><a href="about.html">Who We Are</a></li>
					<li class="dropdown">
						<a href="csr.html" class="dropdown-toggle" data-toggle="dropdown">Sustainability <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a href="csr.html">Environtment</a></li>
							<li class="active"><a href="sidebar-right.html">SOCIAL RESPONSIBILITY</a></li>
						</ul>
					</li>
					<li><a href="career.html">Career</a></li>
					<li><a href="investor.html">Investor</a></li>
				</ul>
			</div><!--/.nav-collapse -->
		</div>
	</div> 
	<!-- /.navbar -->
	
	

app/views/layoutsf/_huh.html.erb
	<!-- Header -->
	<header id="head">
		<div class="container">
			<div class="row">
				<h1 class="lead">EXCELLENCE, PASSION, CUSTOMER, PARTNERS</h1>
				<p class="tagline">Pursuing EXCELLENCE with SIMPLICITY</a></p>
				<p><a class="btn btn-default btn-lg" role="button">Bring to the world a portfolio of quality product that anticipate and satisfy people's desires and needs</a></p>
			</div>
		</div>
	</header>
	<!-- /Header -->

app/views/layoutsf/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layoutsf/_slider.html.erb
<div id="mainCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#mainCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#mainCarousel" data-slide-to="1"></li>
        <li data-target="#mainCarousel" data-slide-to="2"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img src="http://placehold.it/1920x650/777/fff&amp;text=First+Slide" alt="...">
          <div class="carousel-caption">
            <h3>Slide Caption</h3>
          </div>
        </div>
        <div class="item">
          <img src="http://placehold.it/1920x650/777/fff&amp;text=Second+Slide" alt="...">
          <div class="carousel-caption">
            <h3>Slide Caption</h3>
          </div>
        </div>
        <div class="item">
          <img src="http://placehold.it/1920x650/777/fff&amp;text=Third+Slide" alt="...">
          <div class="carousel-caption">
            <h3>Slide Caption</h3>
          </div>
        </div>
      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#mainCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#mainCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span>
      </a>
</div>


 <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>

    <!-- Bootstrap JavaScript -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>

    <!-- Custom JavaScript -->
    <script src="js/custom.js"></script>

    <!-- Call functions on document ready -->
    <script>
        $(document).ready(function() {
            // Call Functions Like
            appMaster.aFunction();
            // Call anotherFunction
            appMaster.anotherFunction();
        });
    </script>

app/views/layoutsf/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  
  <% if false %>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
<% end %>

  <body>
    <%= render 'layouts/header' %>
    <%= render partial: "layouts/huh" if current_page?('/')  %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>







</html>

app/views/static_pagef/about.html.erb
<% provide(:title, "About") %>

 <div class="container">
<h1 class="judul text-center">About Us</h1>

<h2 class="judul">Company Highlights</h2>
<p class="text-justify">
Our history begins in 1866, with the foundation of the Barmin Company. Mr. Robert Barmin develops a breakthrough infant food in 1867, and in 1905 the company he founded merges with USA company, to form what is now known as the Rich Group. During this period cities grow and railways and steamships bring down commodity costs, spurring international trade in consumer goods.
</p>
<%= image_tag 'http://per-concept.com/Rich_Template/images/resource/5.jpg' %>

<h2 class="judul">In 1990 We started as a small business</h2>
<p>
Our brothers helped establish this consulting Company. The issue was to augment long-term resources and working capital and to enhance the leverage ability of the company. In the span of 20 years the company had fortified their presence in the market on account of their focused business segment a wide geographical an effective credit monitoring and appraisal system which has resulted in high growth in business During the year 2003-04 the company increased the windmills capacity from 4450 kwh to 8650 kwh for producing electricity.
</p>


<h2 class="judul">In 1992 We got first recognition</h2>
<p>
  Our brothers helped establish this consulting Company. The issue was to augment long-term resources and working capital and to enhance the leverage ability of the company. In the span of 20 years the company had fortified their presence in the market on account of their focused business segment a wide geographical an effective credit monitoring and appraisal system which has resulted in high growth in business During the year 2003-04 the company increased the windmills capacity from 4450 kwh to 8650 kwh for producing electricity.
</p>
<%= image_tag 'http://per-concept.com/Rich_Template/images/resource/6.jpg' %>


<h2 class="judul">In 2000 we got first Award</h2>
<p>
  Our brothers helped establish this consulting Company. The issue was to augment long-term resources and working capital and to enhance the leverage ability of the company. In the span of 20 years the company had fortified their presence in the market on account of their focused business segment a wide geographical an effective credit monitoring and appraisal system which has resulted in high growth in business During the year 2003-04 the company increased the windmills capacity from 4450 kwh to 8650 kwh for producing electricity.
</p>
<%= image_tag 'http://per-concept.com/Rich_Template/images/resource/7.jpg' %>


<h2></h2>
<p>
  
</p>
<%= image_tag '' %>

</div>

app/views/static_pagef/career.html.erb
 <div class="container">
<h1 class="judul text-center">There are no vacancy available</h1>


<h2></h2>
<p>
  There are currently no vacancies available.

However, we are always keen to meet energetic and talented professionals who would like to join our team.

If you wish to be considered for any future positions, please send your CV and covering letter to :

hrd@barminpacific.com
</p>
<%= image_tag 'https://ideazfirst.com/wp-content/uploads/2016/07/career.jpg' %>

</div>

app/views/static_pagef/csr.html.erb
<% provide(:title, "Help") %>
<h1 class="judul text-center">SOCIAL RESPONSIBILITY</h1>

<div class="container">
  
<%= image_tag 'http://www.arystalifesciencepk.com/datafiles/page_images/93d11dc7c666f8acacf5fe7649a341c9.jpg' %>
<p class="text-justify">


Our social responsibility practices are engraved in our 100+ year history. We believe that building a strong society is key to the growth of our business and the sustainable development of the regions where we operate. Because of this, we seek to add value in every community where we operate.

Gerdau Institute

The Gerdau Institute is responsible for our company's social responsibility policies and guidelines and for promoting social responsibility activities aligned with its business activities. Over the past few years, the Gerdau Institute has standardized and internationalized its practices by applying management methodologies to social projects' planning, implementation and monitoring in order to achieve better results. 

Gerdau Institute's Scope 

The Institute coordinates social responsibility programs within communities, business chain and strategic partners where our company operates through organized volunteering work as an agent for sustainable development.
</p>


</div>

app/views/static_pagef/home.html.erb
<% if false %>

<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", '#', class: "btn btn-lg btn-primary" %>
</div>

<% end %>




	<!-- Intro -->
	<div class="container text-center">
		<br> <br>
		<h2 class="thin">The best place to tell people why they are here</h2>
		<p class="text-muted">
      We sit at the heart of global trading flows, moving product and bulk materials from source to customer as quickly, responsibly and cost-effectively as possible. Our business is founded on the long-term relationships we’ve built with our customers, on our expertise, market understanding and reputation for reliably delivering the required products, on time and on specification.
		</p>
	</div>
	<!-- /Intro-->
		
	<!-- Highlights - jumbotron -->
	<div class="jumbotron top-space">
		<div class="container">
			
			<h3 class="text-center thin">Our Expertise</h3>
			
			<div class="row">
				<div class="col-md-3 col-sm-6 highlight">
					<div class="h-caption"><h4><i class="fa fa-tasks fa-5"></i>Solve problem</h4></div>
					<div class="h-body text-center">
						<p>Every day we use our expertise and logistical networks to distribute new product around the world, efficiently and responsibly. Founded in Rotterdam in 1966, today the company has some 40 offices worldwide and trades over seven million unit of products a day</p>
					</div>
				</div>
				<div class="col-md-3 col-sm-6 highlight">
					<div class="h-caption"><h4><i class="fa fa-heartbeat fa-5"></i>Approach</h4></div>
					<div class="h-body text-center">
						<p>With an industrial presence in 18 countries, we are the leader in all major global markets including automotive, construction, household appliances and packaging, with leading research and development and technology, sizeable captive supplies of raw materials, and outstanding distribution networks. </p>
					</div>
				</div>
				
				
				<div class="col-md-3 col-sm-6 highlight">
					<div class="h-caption"><h4><i class="fa  fa-smile-o fa-5"></i>Bring Happiness</h4></div>
					<div class="h-body text-center">
						<p>We're in the business of spreading smiles and opening happiness every day all across the world. Share your moments with us. </p>
					</div>
				</div>
				
				
				<div class="col-md-3 col-sm-6 highlight">
					<div class="h-caption"><h4><i class="fa fa-globe fa-5"></i>Global opportunity</h4></div>
					<div class="h-body text-center">
						<p>We aim to give our people every chance to flourish in their career and grow as part of a global company. Barmin University is an invaluable, company-wide resource allowing our people to gain new skills and enhance their careers. </p>
					</div>
				</div>
				
			</div> <!-- /row  -->
		
		</div>
	</div>
	<!-- /Highlights -->

	<!-- container -->
	<div class="container">

		<h2 class="text-center top-space">Frequently Asked Questions</h2>
		<br>

		<div class="row">
			<div class="col-sm-6">
				<h3>Which code editor would you recommend?</h3>
				<p>I'd highly recommend you <a href="http://www.sublimetext.com/">Sublime Text</a> - a free to try text editor which I'm using daily. Awesome tool!</p>
			</div>
			<div class="col-sm-6">
				<h3>Nice header. Where do I find more images like that one?</h3>
				<p>
					Well, there are thousands of stock art galleries, but personally, 
					I prefer to use photos from these sites: <a href="http://unsplash.com">Unsplash.com</a> 
					and <a href="http://www.flickr.com/creativecommons/by-2.0/tags/">Flickr - Creative Commons</a></p>
			</div>
		</div> <!-- /row -->

		<div class="row">
			<div class="col-sm-6">
				<h3>Can I use it to build a site for my client?</h3>
				<p>
					Yes, you can. You may use this template for any purpose, just don't forget about the <a href="http://creativecommons.org/licenses/by/3.0/">license</a>, 
					which says: "You must give appropriate credit", i.e. you must provide the name of the creator and a link to the original template in your work. 
				</p>
			</div>
			<div class="col-sm-6">
				<h3>Can you customize this template for me?</h3>
				<p>Yes, I can. Please drop me a line to sergey-at-pozhilov.com and describe your needs in details. Please note, my services are not cheap.</p>
			</div>
		</div> <!-- /row -->

		<div class="jumbotron top-space">
			<h4>Dicta, nostrum nemo soluta sapiente sit dolor quae voluptas quidem doloribus recusandae facere magni ullam suscipit sunt atque rerum eaque iusto facilis esse nam veniam incidunt officia perspiciatis at voluptatibus. Libero, aliquid illum possimus numquam fuga.</h4>
     		<p class="text-right"><a class="btn btn-primary btn-large">Learn more »</a></p>
  		</div>

</div>	<!-- /container -->

app/views/static_pagef/investor.html.erb
<% provide(:title, "Investor") %>

 <div class="container">
<h1 class="judul text-center">Investor</h1>


<h2></h2>
<p>
  Here you can download annual, financial and environmental reports of our parent company Barmin Pacific Ltd.
</p>
<%= image_tag 'https://www.kurita.eu/assets/images/f/Library_Reports-43e0162f.jpg' %>

</div>